apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dkv-peer-cert
  namespace: default
spec:
  secretName: dkv-peer-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations: [My Awesome Company]
    countries: [FR]
    organizationalUnits: [IT]
    localities: [Paris]
  commonName: dkv.default.svc.cluster.local
  dnsNames:
    - dkv.default.svc.cluster.local
    - dkv-0.dkv.default.svc.cluster.local
    - dkv-1.dkv.default.svc.cluster.local
    - dkv-2.dkv.default.svc.cluster.local
  issuerRef:
    name: private-cluster-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - client auth
    - key encipherment
    - digital signature
