apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dkv.example.com-cert
  namespace: default
spec:
  secretName: dkv.example.com-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations: [My Awesome Company]
    countries: [FR]
    organizationalUnits: [IT]
    localities: [Paris]
  commonName: dkv.example.com
  dnsNames:
    - dkv.example.com
  issuerRef:
    name: private-cluster-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - key encipherment
    - digital signature
