apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  secretName: root-ca-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations: [My Awesome Company]
    countries: [FR]
    organizationalUnits: [IT]
    localities: [Paris]
  commonName: My Root CA
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
