apiVersion: v1
kind: Service
metadata:
  name: dkv
spec:
  clusterIP: None
  selector:
    app: dkv
  ports:
    - port: 2380
      name: raft
      targetPort: raft
    - port: 3000
      name: http
      targetPort: http
