apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dkv
spec:
  selector:
    matchLabels:
      app: dkv
  serviceName: dkv
  replicas: 3
  template:
    metadata:
      labels:
        app: dkv
    spec:
      containers:
        - name: dkv
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - containerPort: 2380
              name: raft
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
